import { createContext, useContext, useState } from "react";

export type Lang = "ru" | "en";

const translations = {
  ru: {
    langToggle: "English",
    slogan: "Безопасно. Анонимно. Без следов.",
    phoneLabel: "ВВЕДИТЕ НОМЕР ДОСТУПА",
    phonePlaceholder: "+",
    initiateBtn: "НАЧАТЬ СОЕДИНЕНИЕ",
    initiating: "ПОДКЛЮЧЕНИЕ...",
    codeLabel: "ВВЕДИТЕ КОД ПОДТВЕРЖДЕНИЯ",
    codeHint: "Перехваченный код:",
    verifyBtn: "УСТАНОВИТЬ ЗАЩИЩЁННЫЙ КАНАЛ",
    verifying: "ДЕШИФРОВКА...",
    invalidPhone: "Неверный номер телефона",
    invalidCode: "Неверный код подтверждения!",
    searchPlaceholder: "Поиск в сети...",
    noMessages: "[ НЕТ ПРЕДЫДУЩИХ ЗАЩИЩЁННЫХ СООБЩЕНИЙ ]",
    transmitting: "...передача",
    messagePlaceholder: "Введите зашифрованное сообщение...",
    sendBtn: "ОТПРАВИТЬ",
    selectNode: "[ ВЫБЕРИТЕ УЗЕЛ ДЛЯ УСТАНОВКИ СВЯЗИ ]",
    e2e: "E2E ЗАШИФРОВАНО",
    navComms: "Чаты",
    navSettings: "Настройки",
    navDisconnect: "Выйти",
    navProfile: "Профиль",
    settingsTitle: "Конфигурация системы",
    settingsSubtitle: "Управление безопасностью узла и протоколами доступа.",
    settingsBack: "← Назад",
    doubleBottomTitle: "Двойное дно",
    doubleBottomDesc: "Настройте двойные ключи шифрования. Хранится локально. Только демо.",
    doubleBottomSubDesc: "Двойные пароли, двойной уровень защиты",
    primaryKey: "ОСНОВНОЙ КЛЮЧ ДЕШИФРОВАНИЯ",
    secondaryKey: "ВТОРИЧНЫЙ (СКРЫТЫЙ) КЛЮЧ ДЕШИФРОВАНИЯ",
    commitKeys: "СОХРАНИТЬ КЛЮЧИ",
    keysUpdated: "Ключи шифрования обновлены локально.",
    panicTitle: "Экстренная очистка",
    panicSubDesc: "Немедленное уничтожение всех данных сессии",
    panicDesc: "Выполнение паник-последовательности немедленно уничтожит локальные данные сессии и разорвёт все активные соединения. Действие необратимо.",
    panicLabel: "ВВЕДИТЕ КОД АВТОРИЗАЦИИ ДЛЯ ОЧИСТКИ",
    panicPlaceholder: "напр. 0000",
    panicBtn: "ВЫПОЛНИТЬ ОЧИСТКУ",
    adminTitle: "Сетевой надзор",
    adminSubtitle: "Административный доступ к узлу",
    systemNominal: "СИСТЕМА В НОРМЕ",
    registeredNodes: "Зарегистрированные узлы",
    colIdName: "ID / Имя",
    colIdentifier: "Идентификатор",
    colComms: "Сообщений",
    noNodes: "УЗЛЫ НЕ ОБНАРУЖЕНЫ",
    interceptedTraffic: "Перехваченный трафик",
    route: "МАРШРУТ",
    noTraffic: "ТРАФИК НЕ ОБНАРУЖЕН",
    // Cybersecurity
    cyberTitle: "Кибербезопасность",
    cyberSubtitle: "Расширенные параметры защиты и приватности",
    cyberSubDesc: "Расширенная защита, приватность, сеть, боты",
    privacySection: "Конфиденциальность",
    forwardRestrict: "Запрет пересылки сообщений",
    forwardRestrictDesc: "Запрещает пересылать твои сообщения в другие чаты",
    forwardAll: "Всем",
    forwardContacts: "Контактам",
    forwardNone: "Никому",
    hidePhone: "Скрыть номер телефона",
    hidePhoneDesc: "Номер виден только тебе, даже через API",
    onlineVisibility: "Кто видит мой онлайн",
    onlineVisDesc: "Управляет видимостью статуса «в сети»",
    whoCanMessage: "Кто может писать мне",
    whoCanMessageDesc: "Фильтр входящих сообщений",
    optAll: "Всем",
    optContacts: "Контактам",
    optNone: "Никому",
    hideReadReceipts: "Скрыть прочтение",
    hideReadReceiptsDesc: "Не показывать синие галочки и «прочитано»",
    chatsSection: "Чаты и сообщения",
    burnAfterRead: "Сгорающие сообщения",
    burnAfterReadDesc: "Сообщение удаляется у обоих после прочтения",
    burnOff: "Выкл",
    burn5s: "5 сек",
    burn30s: "30 сек",
    burn1m: "1 мин",
    screenshotBlock: "Запрет скриншотов",
    screenshotBlockDesc: "Блокировка скриншотов в чате",
    invisiblePhoto: "Невидимый просмотр фото",
    invisiblePhotoDesc: "Собеседник не узнает, что ты открыл его фото",
    confirmSend: "Подтверждение перед отправкой",
    confirmSendDesc: "Предпросмотр и кнопка «Отправить» перед передачей",
    quickDeleteMsg: "Быстрое удаление сообщений",
    quickDeleteDesc: "Удалить сообщение в любое время у всех участников",
    accountSection: "Приватность аккаунта",
    appMasquerade: "Маскировка приложения",
    appMasqueradeDesc: "Иконка и название маскируются под другую программу",
    maskOff: "Нет",
    maskCalc: "Калькулятор",
    maskWeather: "Погода",
    maskNotes: "Заметки",
    screenLock: "Шторка экрана",
    screenLockDesc: "При сворачивании — чат блокируется автоматически",
    biometrics: "Биометрия на вход",
    biometricsDesc: "Отпечаток пальца или FaceID для входа в приложение",
    networkSection: "Сеть и данные",
    airGap: "Офлайн-чат (AirGap)",
    airGapDesc: "Обмен сообщениями через Bluetooth/Wi-Fi без интернета",
    autoClearCache: "Автоочистка кэша",
    autoClearCacheDesc: "Удаляет временные файлы из памяти",
    cacheDaily: "Ежедневно",
    cacheWeekly: "Еженедельно",
    cacheNever: "Никогда",
    trafficEncryption: "Шифрование трафика",
    trafficEncryptionDesc: "Дополнительный слой шифрования поверх основного",
    usageMetrics: "Метрика использования",
    usageMetricsDesc: "Отправлять анонимную статистику (можно отключить)",
    botsSection: "Боты и автоматизация",
    botVerification: "Проверка ботов перед запуском",
    botVerificationDesc: "Бот не запустится при обнаружении подозрительных паттернов",
    botRateLimit: "Лимит запросов от бота",
    botRateLimitDesc: "Ограничение частоты запросов к API от ботов",
    rate5: "5/мин",
    rate10: "10/мин",
    rate20: "20/мин",
    groupBots: "Чат-боты в группах",
    groupBotsDesc: "Могут ли боты присутствовать в групповых чатах",
    botsAllowed: "Разрешены",
    botsForbidden: "Запрещены",
    botsVerified: "Проверенные",
    notifsSection: "Уведомления",
    notifMimicry: "Мимикрия уведомлений",
    notifMimicryDesc: "Уведомления маскируются под системные сообщения",
    hiddenNotifText: "Скрытый текст в уведомлениях",
    hiddenNotifTextDesc: "Показывать ли текст сообщения в уведомлении",
    notifAlways: "Всегда",
    notifUnlocked: "При разблокировке",
    notifNever: "Никогда",
    vibroPassword: "Вибро-пароль",
    vibroPasswordDesc: "Вибросигнал для подтверждения открытия уведомления",
    vibroSet: "Настроить паттерн",
    on: "Вкл",
    off: "Выкл",
    // Profile
    profileTitle: "Профиль агента",
    profileSubtitle: "Идентификационные данные узла",
    profileName: "ИМЯ АГЕНТА",
    profilePhone: "НОМЕР ДОСТУПА",
    profileSession: "СЕССИЯ",
    profileMsgCount: "Сообщений отправлено",
    profileOnline: "СТАТУС",
    profileOnlineVal: "В СЕТИ",
    profileEditName: "Изменить имя",
    profileSave: "Сохранить",
    profileCancel: "Отмена",
    profileLogout: "РАЗОРВАТЬ СОЕДИНЕНИЕ",
    profileSaved: "Имя обновлено",
    profileProtocol: "ПРОТОКОЛ",
    profileProtocolVal: "AES-256-GCM",
  },
  en: {
    langToggle: "Русский",
    slogan: "Secure. Anonymous. Untraceable.",
    phoneLabel: "ENTER NODE ACCESS NUMBER",
    phonePlaceholder: "+",
    initiateBtn: "INITIATE HANDSHAKE",
    initiating: "CONNECTING...",
    codeLabel: "VERIFICATION MATRIX REQUIRED",
    codeHint: "Intercepted code:",
    verifyBtn: "ESTABLISH SECURE LINK",
    verifying: "DECRYPTING...",
    invalidPhone: "Invalid phone number",
    invalidCode: "Invalid verification code!",
    searchPlaceholder: "Scan network...",
    noMessages: "[ NO PREVIOUS SECURE COMMS DETECTED ]",
    transmitting: "...transmitting",
    messagePlaceholder: "Enter secure message...",
    sendBtn: "SEND",
    selectNode: "[ SELECT NODE TO ESTABLISH LINK ]",
    e2e: "E2E ENCRYPTED",
    navComms: "Comms",
    navSettings: "Settings",
    navDisconnect: "Disconnect",
    navProfile: "Profile",
    settingsTitle: "System Configuration",
    settingsSubtitle: "Manage node security and access protocols.",
    settingsBack: "← Back",
    doubleBottomTitle: "Double Bottom",
    doubleBottomDesc: "Configure dual encryption keys. Stored locally. Feature demo only.",
    doubleBottomSubDesc: "Dual passwords, dual layer protection",
    primaryKey: "PRIMARY DECRYPTION KEY",
    secondaryKey: "SECONDARY (HIDDEN) DECRYPTION KEY",
    commitKeys: "COMMIT KEYS TO STORAGE",
    keysUpdated: "Encryption keys updated locally.",
    panicTitle: "Emergency Purge",
    panicSubDesc: "Immediate destruction of all session data",
    panicDesc: "Executing panic sequence will immediately destroy local session data and sever all active connections. This action cannot be reversed.",
    panicLabel: "ENTER AUTHORIZATION CODE TO PURGE",
    panicPlaceholder: "e.g. 0000",
    panicBtn: "EXECUTE PURGE",
    adminTitle: "Network Overwatch",
    adminSubtitle: "Administrative Node Access",
    systemNominal: "SYSTEM NOMINAL",
    registeredNodes: "Registered Nodes",
    colIdName: "ID / Name",
    colIdentifier: "Identifier",
    colComms: "Comms",
    noNodes: "NO NODES DETECTED",
    interceptedTraffic: "Intercepted Traffic",
    route: "ROUTE",
    noTraffic: "NO TRAFFIC DETECTED",
    // Cybersecurity
    cyberTitle: "Cybersecurity",
    cyberSubtitle: "Advanced protection and privacy parameters",
    cyberSubDesc: "Advanced protection, privacy, network, bots",
    privacySection: "Privacy",
    forwardRestrict: "Message forwarding restriction",
    forwardRestrictDesc: "Prevents your messages from being forwarded to other chats",
    forwardAll: "Everyone",
    forwardContacts: "Contacts",
    forwardNone: "Nobody",
    hidePhone: "Hide phone number",
    hidePhoneDesc: "Number visible only to you, even via API",
    onlineVisibility: "Who can see my online",
    onlineVisDesc: "Controls online status visibility",
    whoCanMessage: "Who can message me",
    whoCanMessageDesc: "Incoming message filter",
    optAll: "Everyone",
    optContacts: "Contacts",
    optNone: "Nobody",
    hideReadReceipts: "Hide read receipts",
    hideReadReceiptsDesc: "Don't show blue ticks and read status",
    chatsSection: "Chats & Messages",
    burnAfterRead: "Burn after read",
    burnAfterReadDesc: "Message deleted for both after reading",
    burnOff: "Off",
    burn5s: "5 sec",
    burn30s: "30 sec",
    burn1m: "1 min",
    screenshotBlock: "Screenshot block",
    screenshotBlockDesc: "Block screenshots in chat",
    invisiblePhoto: "Invisible photo view",
    invisiblePhotoDesc: "Recipient won't know you opened their photo",
    confirmSend: "Confirm before send",
    confirmSendDesc: "Preview and confirm before transmitting",
    quickDeleteMsg: "Quick message delete",
    quickDeleteDesc: "Delete messages for all participants at any time",
    accountSection: "Account Privacy",
    appMasquerade: "App masquerade",
    appMasqueradeDesc: "Icon and name disguised as another app",
    maskOff: "None",
    maskCalc: "Calculator",
    maskWeather: "Weather",
    maskNotes: "Notes",
    screenLock: "Screen lock",
    screenLockDesc: "Chat locks automatically when app is minimized",
    biometrics: "Biometric entry",
    biometricsDesc: "Fingerprint or FaceID to enter the app",
    networkSection: "Network & Data",
    airGap: "Offline chat (AirGap)",
    airGapDesc: "Exchange messages via Bluetooth/Wi-Fi without internet",
    autoClearCache: "Auto-clear cache",
    autoClearCacheDesc: "Delete temporary files from memory",
    cacheDaily: "Daily",
    cacheWeekly: "Weekly",
    cacheNever: "Never",
    trafficEncryption: "Traffic encryption",
    trafficEncryptionDesc: "Additional encryption layer on top of the base",
    usageMetrics: "Usage metrics",
    usageMetricsDesc: "Send anonymous statistics (can be disabled)",
    botsSection: "Bots & Automation",
    botVerification: "Verify bots before launch",
    botVerificationDesc: "Bot won't launch if suspicious patterns are detected",
    botRateLimit: "Bot request limit",
    botRateLimitDesc: "Limit bot API request frequency",
    rate5: "5/min",
    rate10: "10/min",
    rate20: "20/min",
    groupBots: "Bots in groups",
    groupBotsDesc: "Whether bots can be present in group chats",
    botsAllowed: "Allowed",
    botsForbidden: "Forbidden",
    botsVerified: "Verified only",
    notifsSection: "Notifications",
    notifMimicry: "Notification mimicry",
    notifMimicryDesc: "Notifications disguised as system messages",
    hiddenNotifText: "Hidden notification text",
    hiddenNotifTextDesc: "Whether to show message text in notification",
    notifAlways: "Always",
    notifUnlocked: "When unlocked",
    notifNever: "Never",
    vibroPassword: "Vibro-password",
    vibroPasswordDesc: "Vibration pattern to confirm opening notification",
    vibroSet: "Set pattern",
    on: "On",
    off: "Off",
    // Profile
    profileTitle: "Agent Profile",
    profileSubtitle: "Node identification data",
    profileName: "AGENT NAME",
    profilePhone: "ACCESS NUMBER",
    profileSession: "SESSION",
    profileMsgCount: "Messages sent",
    profileOnline: "STATUS",
    profileOnlineVal: "ONLINE",
    profileEditName: "Change name",
    profileSave: "Save",
    profileCancel: "Cancel",
    profileLogout: "SEVER CONNECTION",
    profileSaved: "Name updated",
    profileProtocol: "PROTOCOL",
    profileProtocolVal: "AES-256-GCM",
  },
} as const;

export type Translations = Record<keyof typeof translations.ru, string>;

interface LangContextType {
  lang: Lang;
  t: Translations;
  toggleLang: () => void;
}

const LangContext = createContext<LangContextType | null>(null);

export function LangProvider({ children }: { children: React.ReactNode }) {
  const stored = (localStorage.getItem("shifr_lang") as Lang) || "ru";
  const [lang, setLang] = useState<Lang>(stored);

  const toggleLang = () => {
    const next: Lang = lang === "ru" ? "en" : "ru";
    setLang(next);
    localStorage.setItem("shifr_lang", next);
  };

  return (
    <LangContext.Provider value={{ lang, t: translations[lang], toggleLang }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used inside LangProvider");
  return ctx;
}
